version: '2'
services:
  web:
    image: odoo:{odoo_version}.0
    depends_on:
      - db
    ports:
      - "81{odoo_version}:8069"
      - "80{odoo_version}:80{odoo_version}"
      - "8{odoo_version}71:8071"
      - "8{odoo_version}72:8072"
    volumes:
      - web:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs/odoo-server.log:/var/log/odoo/openerp-server.log
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro      
  db:
    image: postgres:12
    ports:
      - "5432:5432"    
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro      
volumes:
  web:
  db:
