version: '2'
services:
  web:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8115:8069"
      - "8015:8015"
      - "8571:8071"
      - "8572:8072"
    volumes:
      - web:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs/odoo-server.log:/var/log/odoo/openerp-server.log
      - /etc/timezone:/etc/timezone:ro
  db:
    image: postgres:12
    ports:
      - "5432:5432"    
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata
      - /etc/timezone:/etc/timezone:ro
volumes:
  web:
  db:
